name: safe_admin_web
description: SAFE Admin Dashboard - PDAO Management Portal (Flutter Web)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  
  # UI
  cupertino_icons: ^1.0.8
  
  # State Management & Navigation
  provider: ^6.1.2
  go_router: ^14.6.2
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  
  # Maps
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
